server:
  port: ":9090"
  mode: "debug"

jwt:
  secret: "fde923749e4fcf9e90222debf2612219610869b90f6988177f2ef23cf623c43d"

stores:
  mysql:
    connection_string: "username:password@tcp(127.0.0.1:3306)/db_name?charset=utf8mb4&parseTime=True&loc=Local"