definitions:
  responses.FailureBody:
    properties:
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
  responses.SuccessBody:
    properties:
      data: {}
      success:
        type: boolean
    type: object
  schemas.LoginSchema:
    properties:
      email:
        type: string
      password:
        maxLength: 32
        minLength: 8
        type: string
      username:
        type: string
    required:
    - password
    type: object
  schemas.RegisterSchema:
    properties:
      date_of_birth:
        type: string
      email:
        type: string
      first_name:
        maxLength: 50
        minLength: 2
        type: string
      gender:
        enum:
        - male
        - female
        - other
        type: string
      last_name:
        maxLength: 50
        minLength: 2
        type: string
      mobile_number:
        type: string
      password:
        maxLength: 32
        minLength: 8
        type: string
      username:
        type: string
    required:
    - date_of_birth
    - email
    - first_name
    - gender
    - last_name
    - mobile_number
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user with email/username and password, and returns
        a JWT token
      parameters:
      - description: User login data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.LoginSchema'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.SuccessBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.FailureBody'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/responses.FailureBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.FailureBody'
      summary: User login
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Creates a new user with the provided details
      parameters:
      - description: User registration data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.RegisterSchema'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Register a new customer
      tags:
      - Auth
  /placeholder:
    post:
      consumes:
      - application/json
      description: This is a dummp placeholder
      parameters:
      - description: Placeholder sample
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.LoginSchema'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.SuccessBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.FailureBody'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/responses.FailureBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.FailureBody'
      security:
      - AuthorizationToken: []
      summary: Placeholder dummy
      tags:
      - Placeholder
securityDefinitions:
  AuthorizationToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
